spring:
  application.name: azureDemo
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/testAzureDb?useSSL=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${DB_PASSWORD:1111}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      jdbc:
        batch_size: 20
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: classpath:db-changelog.yml
    enabled: true
