spring:
  application.name: azureDemo
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/testAzureDb
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        physical_naming_strategy: io.micronaut.data.hibernate.naming.DefaultPhysicalNamingStrategy

    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: classpath:db-changelog.yml
    enabled: true
